"""initial schema

Revision ID: 05a62086ca6d
Revises: 
Create Date: 2026-09-24 11:22:32.568010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a62086ca6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ab_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ab_register_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('registration_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ab_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ab_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('fail_login_count', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ab_view_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('business_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('object_number', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_revision_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_revision_id'], ['revision.id'], ),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_number')
    )
    op.create_table('object_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_type_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_type_id'], ['object_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('relationship_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('release_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.String(length=40), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['business_object.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'revision_id', name='uq_revision_object_rev')
    )
    op.create_table('revision_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workflow_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('started_on', sa.DateTime(), nullable=True),
    sa.Column('completed_on', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('lookup_hash', sa.String(length=256), nullable=True),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('expires_on', sa.DateTime(), nullable=True),
    sa.Column('revoked_on', sa.DateTime(), nullable=True),
    sa.Column('last_used_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lookup_hash'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('ab_api_key', schema=None) as batch_op:
        batch_op.create_index('idx_api_key_lookup_hash', ['lookup_hash'], unique=True)
        batch_op.create_index('idx_api_key_prefix', ['key_prefix'], unique=False)
        batch_op.create_index('idx_api_key_user_id', ['user_id'], unique=False)

    op.create_table('ab_group_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ab_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'role_id')
    )
    with op.batch_alter_table('ab_group_role', schema=None) as batch_op:
        batch_op.create_index('idx_group_id', ['group_id'], unique=False)
        batch_op.create_index('idx_group_role_id', ['role_id'], unique=False)

    op.create_table('ab_permission_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('view_menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['ab_permission.id'], ),
    sa.ForeignKeyConstraint(['view_menu_id'], ['ab_view_menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_id', 'view_menu_id')
    )
    with op.batch_alter_table('ab_permission_view', schema=None) as batch_op:
        batch_op.create_index('idx_permission_id', ['permission_id'], unique=False)
        batch_op.create_index('idx_view_menu_id', ['view_menu_id'], unique=False)

    op.create_table('ab_user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ab_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id')
    )
    with op.batch_alter_table('ab_user_group', schema=None) as batch_op:
        batch_op.create_index('idx_user_group_id', ['group_id'], unique=False)
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)

    op.create_table('ab_user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id')
    )
    op.create_table('bom_occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_revision_id', sa.Integer(), nullable=False),
    sa.Column('child_revision_id', sa.Integer(), nullable=False),
    sa.Column('find_number', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_revision_id'], ['revision.id'], ),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_rule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['revision_rule_id'], ['revision_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('dataset_type', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'DATE', name='propertydatatype', native_enum=False, length=32), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('multi_value', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type_id', 'name', name='uq_propdef_type_name')
    )
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_type_id', sa.Integer(), nullable=False),
    sa.Column('primary_revision_id', sa.Integer(), nullable=False),
    sa.Column('secondary_revision_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_revision_id'], ['revision.id'], ),
    sa.ForeignKeyConstraint(['relationship_type_id'], ['relationship_type.id'], ),
    sa.ForeignKeyConstraint(['secondary_revision_id'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_lineage',
    sa.Column('parent_revision_id', sa.Integer(), nullable=False),
    sa.Column('child_revision_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_revision_id'], ['revision.id'], ),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('parent_revision_id', 'child_revision_id')
    )
    op.create_table('revision_release_state',
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('release_state_id', sa.Integer(), nullable=False),
    sa.Column('assigned_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['release_state_id'], ['release_state.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('revision_id', 'release_state_id')
    )
    op.create_table('verification_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_revision_id', sa.Integer(), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=True),
    sa.Column('result', sa.String(length=40), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_revision_id'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_state', sa.String(length=40), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['workflow_process.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_permission_view_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_view_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_view_id'], ['ab_permission_view.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_view_id', 'role_id')
    )
    with op.batch_alter_table('ab_permission_view_role', schema=None) as batch_op:
        batch_op.create_index('idx_permission_view_id', ['permission_view_id'], unique=False)
        batch_op.create_index('idx_role_id', ['role_id'], unique=False)

    op.create_table('baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_context_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_context_id'], ['configuration_context.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managed_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occurrence_trace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_revision_id', sa.Integer(), nullable=False),
    sa.Column('bom_occurrence_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bom_occurrence_id'], ['bom_occurrence.id'], ),
    sa.ForeignKeyConstraint(['requirement_revision_id'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('property_definition_id', sa.Integer(), nullable=False),
    sa.Column('string_value', sa.Text(), nullable=True),
    sa.Column('integer_value', sa.Integer(), nullable=True),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_definition_id'], ['property_definition.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'property_definition_id', 'sequence_no', name='uq_propvalue_rev_def_seq')
    )
    op.create_table('baseline_member',
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baseline.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('baseline_id', 'revision_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baseline_member')
    op.drop_table('property_value')
    op.drop_table('occurrence_trace')
    op.drop_table('managed_file')
    op.drop_table('baseline')
    with op.batch_alter_table('ab_permission_view_role', schema=None) as batch_op:
        batch_op.drop_index('idx_role_id')
        batch_op.drop_index('idx_permission_view_id')

    op.drop_table('ab_permission_view_role')
    op.drop_table('workflow_task')
    op.drop_table('verification_result')
    op.drop_table('revision_release_state')
    op.drop_table('revision_lineage')
    op.drop_table('relationship')
    op.drop_table('property_definition')
    op.drop_table('dataset')
    op.drop_table('configuration_context')
    op.drop_table('bom_occurrence')
    op.drop_table('ab_user_role')
    with op.batch_alter_table('ab_user_group', schema=None) as batch_op:
        batch_op.drop_index('idx_user_id')
        batch_op.drop_index('idx_user_group_id')

    op.drop_table('ab_user_group')
    with op.batch_alter_table('ab_permission_view', schema=None) as batch_op:
        batch_op.drop_index('idx_view_menu_id')
        batch_op.drop_index('idx_permission_id')

    op.drop_table('ab_permission_view')
    with op.batch_alter_table('ab_group_role', schema=None) as batch_op:
        batch_op.drop_index('idx_group_role_id')
        batch_op.drop_index('idx_group_id')

    op.drop_table('ab_group_role')
    with op.batch_alter_table('ab_api_key', schema=None) as batch_op:
        batch_op.drop_index('idx_api_key_user_id')
        batch_op.drop_index('idx_api_key_prefix')
        batch_op.drop_index('idx_api_key_lookup_hash')

    op.drop_table('ab_api_key')
    op.drop_table('workflow_process')
    op.drop_table('revision_rule')
    op.drop_table('revision')
    op.drop_table('release_state')
    op.drop_table('relationship_type')
    op.drop_table('object_type')
    op.drop_table('business_object')
    op.drop_table('ab_view_menu')
    op.drop_table('ab_user')
    op.drop_table('ab_role')
    op.drop_table('ab_register_user')
    op.drop_table('ab_permission')
    op.drop_table('ab_group')
    # ### end Alembic commands ###
