"""unique relationship

Revision ID: 1bb38e525b37
Revises: 26f349ed091f
Create Date: 2026-09-25 09:06:57.984967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb38e525b37'
down_revision = '26f349ed091f'
branch_labels = None
depends_on = None


def upgrade():
    # NOTE: this constraint fails if the relationship table already contains
    # duplicate (type, primary, secondary) triples. Remove duplicates before
    # upgrading a pre-existing database, e.g.:
    #   DELETE FROM relationship WHERE id NOT IN
    #     (SELECT MIN(id) FROM relationship
    #       GROUP BY relationship_type_id, primary_revision_id, secondary_revision_id)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_relationship_type_primary_secondary', ['relationship_type_id', 'primary_revision_id', 'secondary_revision_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.drop_constraint('uq_relationship_type_primary_secondary', type_='unique')

    # ### end Alembic commands ###
