"""add foreign key indexes

Revision ID: 26f349ed091f
Revises: 05a62086ca6d
Create Date: 2026-09-25 08:21:57.847932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f349ed091f'
down_revision = '05a62086ca6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baseline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baseline_configuration_context_id'), ['configuration_context_id'], unique=False)

    with op.batch_alter_table('baseline_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baseline_member_revision_id'), ['revision_id'], unique=False)

    with op.batch_alter_table('bom_occurrence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_occurrence_child_revision_id'), ['child_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_occurrence_parent_revision_id'), ['parent_revision_id'], unique=False)

    with op.batch_alter_table('business_object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_object_current_revision_id'), ['current_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_object_object_type_id'), ['object_type_id'], unique=False)

    with op.batch_alter_table('configuration_context', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_context_revision_rule_id'), ['revision_rule_id'], unique=False)

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_revision_id'), ['revision_id'], unique=False)

    with op.batch_alter_table('managed_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_file_dataset_id'), ['dataset_id'], unique=False)

    with op.batch_alter_table('object_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_type_parent_type_id'), ['parent_type_id'], unique=False)

    with op.batch_alter_table('occurrence_trace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occurrence_trace_bom_occurrence_id'), ['bom_occurrence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrence_trace_requirement_revision_id'), ['requirement_revision_id'], unique=False)

    with op.batch_alter_table('property_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_definition_object_type_id'), ['object_type_id'], unique=False)

    with op.batch_alter_table('property_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_value_property_definition_id'), ['property_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_value_revision_id'), ['revision_id'], unique=False)

    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationship_primary_revision_id'), ['primary_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_relationship_type_id'), ['relationship_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_secondary_revision_id'), ['secondary_revision_id'], unique=False)

    with op.batch_alter_table('revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_object_id'), ['object_id'], unique=False)

    with op.batch_alter_table('revision_release_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_release_state_release_state_id'), ['release_state_id'], unique=False)

    with op.batch_alter_table('verification_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_result_test_revision_id'), ['test_revision_id'], unique=False)

    with op.batch_alter_table('workflow_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_task_process_id'), ['process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_task_revision_id'), ['revision_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_task_revision_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_task_process_id'))

    with op.batch_alter_table('verification_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_result_test_revision_id'))

    with op.batch_alter_table('revision_release_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_release_state_release_state_id'))

    with op.batch_alter_table('revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_object_id'))

    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_secondary_revision_id'))
        batch_op.drop_index(batch_op.f('ix_relationship_relationship_type_id'))
        batch_op.drop_index(batch_op.f('ix_relationship_primary_revision_id'))

    with op.batch_alter_table('property_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_value_revision_id'))
        batch_op.drop_index(batch_op.f('ix_property_value_property_definition_id'))

    with op.batch_alter_table('property_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_definition_object_type_id'))

    with op.batch_alter_table('occurrence_trace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occurrence_trace_requirement_revision_id'))
        batch_op.drop_index(batch_op.f('ix_occurrence_trace_bom_occurrence_id'))

    with op.batch_alter_table('object_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_type_parent_type_id'))

    with op.batch_alter_table('managed_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managed_file_dataset_id'))

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_revision_id'))

    with op.batch_alter_table('configuration_context', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_context_revision_rule_id'))

    with op.batch_alter_table('business_object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_object_object_type_id'))
        batch_op.drop_index(batch_op.f('ix_business_object_current_revision_id'))

    with op.batch_alter_table('bom_occurrence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_occurrence_parent_revision_id'))
        batch_op.drop_index(batch_op.f('ix_bom_occurrence_child_revision_id'))

    with op.batch_alter_table('baseline_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baseline_member_revision_id'))

    with op.batch_alter_table('baseline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baseline_configuration_context_id'))

    # ### end Alembic commands ###
