"""unique bom and occurrence trace

Revision ID: b82bd12c1ba6
Revises: 1bb38e525b37
Create Date: 2026-09-25 09:20:08.050222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82bd12c1ba6'
down_revision = '1bb38e525b37'
branch_labels = None
depends_on = None


def upgrade():
    # NOTE: these constraints fail if the tables already contain duplicates.
    # Remove duplicate BOM find numbers / occurrence traces before upgrading a
    # pre-existing database (see the Phase 4 migration for the same pattern).
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bom_occurrence', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_bom_parent_find', ['parent_revision_id', 'find_number'])

    with op.batch_alter_table('occurrence_trace', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_occurrence_trace_req_occ', ['requirement_revision_id', 'bom_occurrence_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occurrence_trace', schema=None) as batch_op:
        batch_op.drop_constraint('uq_occurrence_trace_req_occ', type_='unique')

    with op.batch_alter_table('bom_occurrence', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bom_parent_find', type_='unique')

    # ### end Alembic commands ###
