"""configuration rule type and baseline constraints

Revision ID: eb8e40076f38
Revises: b82bd12c1ba6
Create Date: 2026-09-25 09:37:47.675485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8e40076f38'
down_revision = 'b82bd12c1ba6'
branch_labels = None
depends_on = None


def upgrade():
    # NOTE: the baseline unique constraint fails if a context already has two
    # baselines with the same name; deduplicate first on a pre-existing DB.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baseline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_baseline_context_name', ['configuration_context_id', 'name'])

    with op.batch_alter_table('revision_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_type', sa.Enum('LATEST_WORKING', 'LATEST_RELEASED', name='revisionruletype', native_enum=False, length=40), server_default='LATEST_WORKING', nullable=False))

    # Backfill the rule type for the known seeded rules.
    op.execute(
        "UPDATE revision_rule SET rule_type = 'LATEST_RELEASED' "
        "WHERE name = 'Latest Released'"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revision_rule', schema=None) as batch_op:
        batch_op.drop_column('rule_type')

    with op.batch_alter_table('baseline', schema=None) as batch_op:
        batch_op.drop_constraint('uq_baseline_context_name', type_='unique')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
